# Generated by Django 4.1.7 on 2023-04-10 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_assessor', models.CharField(max_length=50)),
                ('id_chat_a', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('id_chat_d', models.CharField(default='', max_length=20)),
                ('only_assec', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastrar.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ABS', 'ABS AUTO BOMBA SALVAMENTO'), ('ABSR', 'ABSR AUTO BOMBA SALVAMENTO E RESGATE'), ('ABT', 'ABT AUTO BOMBA TANQUE'), ('ABTS', 'ABTS AUTO BOMBA TANQUE SALVAMENTO'), ('ACA', 'ACA AUTO COMANDO DE AREA'), ('ACE', 'ACE AUTO CAÇAMBA ELEVATÓRIA'), ('AE', 'AE AUTOESCOLA'), ('AEM', 'AEM AUTO ESCADA MECANICA'), ('AJ', 'AJ AUTO JAMANTA'), ('AMA', 'AMA AMBULANCIA ADMINISTRATIVA'), ('APE', 'APE AUTO PLATAFORMA ESCADA'), ('APP', 'APP AUTO PRODUTOS PERIGOSOS'), ('APV', 'APV AUTO PATRULHA DE VISTORIA'), ('APV', 'APV AUTO PREVENCAO E VISTORIA'), ('AR', 'AR AUTO REBOQUE'), ('ASF', 'ASF AUTO SALVAMENTO FLORESTAL'), ('ASL', 'ASL AUTO SALVAMENTO LEVE'), ('ASM', 'ASM AUTO SALVAMENTO MEDIO'), ('ASP', 'ASP AUTO SALVAMENTO PESADO'), ('ATB', 'ATB AUTO TANQUE BOMBA'), ('AUTO', 'AUTO ATENDIMENTO DOMICILIAR TERAPEUTICO'), ('MB', 'MB MOTO DE BOMBEIRO'), ('MO', 'MO MOTO OPERACIONAL'), ('NÃO', 'NÃO INFORMADO'), ('TAN', 'TAN TRANSPORTE DE ANIMAIS'), ('TC', 'TC TRANSPORTE DE CARGA'), ('TCA', 'TCA TRANSPORTE DE COMBUSTIVEL DE AVIACAO'), ('TCE', 'TCE TRANSPORTE DE COORDENACAO ESTRATEGICA'), ('TE', 'TE TRANSPORTE ESPECIALIZADO'), ('TLP', 'TLP TRANSPORTE LEVE DE PESSOAL'), ('TP', 'TP TRANSPORTE DE PESSOAL'), ('TPP', 'TPP TRANSPORTE PESADO DE PESSOAL'), ('TR', 'TR TRANSPORTE DE REPRESENTACOES'), ('UR', 'UR UNIDADE DE RESGATE'), ('VA', 'VA VIATURAS ADMINISTRATIVAS'), ('VRM', 'VRM VEICULO DE ROTA DE MANUTENCA')], default='UR', max_length=9)),
                ('placa', models.CharField(max_length=7)),
                ('titular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastrar.titular')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDisparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('viatura', models.CharField(blank=True, max_length=10, null=True)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastrar.assessor')),
                ('disparador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastrar.titular')),
            ],
        ),
        migrations.AddField(
            model_name='assessor',
            name='titular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastrar.titular'),
        ),
    ]
