# Generated by Django 4.1.7 on 2023-04-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='titular',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
