# Generated by Django 4.1.7 on 2023-04-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0002_assessor_telefone_titular_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessor',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='titular',
            name='telefone',
        ),
        migrations.AddField(
            model_name='assessor',
            name='ddd',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='telfnumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='titular',
            name='ddd',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='titular',
            name='telfnumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
