# Generated by Django 4.1.7 on 2023-04-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0005_alter_assessor_ddd_alter_titular_ddd'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjudaManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=40)),
                ('id_user', models.CharField(blank=True, max_length=15)),
                ('categoria', models.CharField(blank=True, max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('mensagem', models.CharField(blank=True, max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
