# Generated by Django 4.1.7 on 2023-04-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0006_ajudamanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajudamanager',
            name='mensagem',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
