# Generated by Django 4.1.7 on 2023-04-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0007_alter_ajudamanager_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajudamanager',
            name='tema',
            field=models.CharField(choices=[('1', '1 - DIFICULDADE DE ACESSO'), ('2', '2 - ERRO NOS DADOS'), ('3', '3 - NÃO RECEBO MAIS DADOS'), ('4', '4 - NÃO QUERO MAIS RECEBER DADOS'), ('5', '5 - TROQUEI DE TITULAR'), ('6', '6 - OUTRO')], default=False, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ajudamanager',
            name='categoria',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
