# Generated by Django 4.1.7 on 2023-04-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0008_ajudamanager_tema_alter_ajudamanager_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajudamanager',
            name='tema',
            field=models.CharField(choices=[('DA', 'DIFICULDADE DE ACESSO'), ('ED', 'ERRO NOS DADOS'), ('NRD', 'NÃO RECEBO MAIS DADOS'), ('NQD', 'NÃO QUERO MAIS RECEBER DADOS'), ('TT', 'TROQUEI DE TITULAR'), ('OT', 'OUTRO')], max_length=40),
        ),
    ]
