# Generated by Django 4.1.7 on 2023-04-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0010_alter_ajudamanager_tema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajudamanager',
            name='telefone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='telfnumber',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='titular',
            name='telfnumber',
            field=models.CharField(max_length=255),

        ),
    ]
