# Generated by Django 4.1.7 on 2023-04-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0011_alter_ajudamanager_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajudamanager',
            name='telefone',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='telfnumber',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='titular',
            name='telfnumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
