# Generated by Django 4.1.7 on 2023-04-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0012_alter_ajudamanager_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='telfnumber',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='titular',
            name='telfnumber',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
