# Generated by Django 4.1.7 on 2023-04-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0013_alter_assessor_telfnumber_alter_titular_telfnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='telfnumber',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='titular',
            name='telfnumber',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
