# Generated by Django 4.1.7 on 2023-04-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0015_alter_assessor_telfnumber_alter_titular_telfnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajudamanager',
            name='telefone',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
