# Generated by Django 4.1.7 on 2023-05-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0018_alter_ajudamanager_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajudamanager',
            name='telefone',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
