# Generated by Django 4.1.7 on 2023-04-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disparo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regassessor',
            name='ddd',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='regassessor',
            name='telfnumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='regtitular',
            name='ddd',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='regtitular',
            name='telfnumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
