# Generated by Django 4.1.7 on 2023-04-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disparo', '0002_regassessor_ddd_regassessor_telfnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditAssessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ass', models.CharField(blank=True, max_length=50)),
                ('id_tit_new', models.CharField(blank=True, max_length=50)),
                ('id_tit_old', models.CharField(blank=True, max_length=50)),
                ('telegram_id', models.CharField(blank=True, max_length=15)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
