# Generated by Django 4.1.7 on 2023-04-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disparo', '0004_editassessor_telefone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditAssessor',
        ),
    ]
