# Generated by Django 4.1.7 on 2023-04-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disparo', '0005_delete_editassessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regassessor',
            name='telfnumber',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='regtitular',
            name='telfnumber',
            field=models.CharField(max_length=255),
        ),
    ]
