# Generated by Django 4.1.7 on 2023-04-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disparo', '0006_alter_regassessor_telfnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regassessor',
            name='telfnumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='regtitular',
            name='telfnumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
