# Generated by Django 4.1.7 on 2023-05-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disparo', '0010_alter_regassessor_telfnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regassessor',
            name='id_a',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='regassessor',
            name='nome_ass',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='regassessor',
            name='nome_cat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='regassessor',
            name='nome_tit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='regassessor',
            name='telfnumber',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='regtitular',
            name='id_t',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='regtitular',
            name='nome_cat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='regtitular',
            name='nome_tit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
