# Generated by Django 4.1.7 on 2023-04-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ddd',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='telfnumber',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
