# Generated by Django 4.1.7 on 2023-04-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_users_ddd_users_telfnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprovUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('cargo', models.CharField(default='D', max_length=1)),
                ('ddd', models.CharField(blank=True, max_length=2, null=True)),
                ('telfnumber', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
