# Generated by Django 4.1.7 on 2023-04-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_aprovuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprovuser',
            name='password',
            field=models.CharField(max_length=260),
        ),
    ]
