# Generated by Django 4.1.7 on 2023-05-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_aprovuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprovuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='aprovuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aprovuser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aprovuser',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='aprovuser',
            name='telfnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aprovuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='telfnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
